[build]
  command = "npm run build:site"
  publish = "dist"

[[redirects]]
  from = "/about-us"
  to = "/about-us.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/contact-us"
  to = "/contact-us.html"
  status = 200

[[redirects]]
  from = "/disclaimer"
  to = "/disclaimer.html"
  status = 200

[[redirects]]
  from = "/download"
  to = "/download.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-of-service.html"
  status = 200


